name: Deploy website

on:
  push:
    branches:
      - main

jobs:

  deploy:  

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: configure SSH
        run: | 
          mkdir -p ~/.ssh
          
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa

          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy website
        run: |
          scp index.html ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/

      - name: Deploy website
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo cp /tmp/index.html /usr/share/nginx/html/index.html
          sudo systemctl restart nginx"