name: First workflow

on:
  push:

jobs:

  hello: 

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Explore runner
        run: | 
          whoami
          pwd
          ls -la
          uname -a
